language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: "Of0PvP2/3zeu0FONlBtMMkIH2/cBbLosqc2mMY3ncW1rcHJrxVdr/6gAW+4/Hp8eyWivb5LLNvkr/STOcg3zPdM6RZp8L95gDjeiLdHtVJDHEfaKcODeEK2jft1p9alRbw5g/9GwqkNwbjYvpRV//VQ143UQNODr/IacNfEtb6YyeQbqf9xUMUYIrfK0lf+Xm25LsYKi/OZP5IqMdd8G4TLoZoiFx3leTc6lBk6UmeMr5TuAOcMFpK2h+cOrPUsGGOHkEBBglWJ/DVhbVMSrDzUsWFGvPAIQgxY3+1DPQv7mNzWcDuwb8xkjo3Fi9ABoThmA9rYeJ8XkbBhIzJfgGs4f8nzBR+ENzhYHoafyahA1CT0S19gl50ojoub7x7C4a4f+C6nZ9CNaCm5Wm6EeKBSQLEMdWXVah7R48fMRIDRCGrLMMAiIpAZqLPVayQ3D7F1+UiJvpFjmFUSdUJFC1ZgKjibqtG64fuyOLniWt1ERVlwtKNVhM+2cg8v11JzdXzuJBjMgIz2EnG8tafCGlPgzGSI+f6DTYoRsdyoTxo0AzTKolQ6J7NynOy5Moo/kJzqDljzRRzmPbSiRf6lXxGL/0qZbKrVavmd36EiPFFQd5U5OxMJkEvmD7d/tIqb5g34f1fPqXlLuUMibzVEEieeIyEXPb0GnoS2AR4teMO8="
script:
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN