language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: "mbKWumOWsB72WLbg+KpSgHaCyAp5SZ2+ZsQhVs+bEsKwkshnehLhLxYWl2/9jt5OUDwmPI5WdSlMkj6BWJWCcvpmUbh9hYy19NLXU1VokEQXaVCdKEA8mxFLeqj+IY4urXj3kZAxtx8LiHvn48Ydy/nR2ZMCRQdO4HADWCVnsiblL4hoX09c46teLVDnrRNmcK1pkOQ5XFRcd8G8m/IQX0CfsjrFYJ204uhqWe0AoVfQugTr/E0QPj1sl9xOuHipm6L9y2Kx6w7uWMQQeknRXzyYBvU8UHoN+s+gYADNjUAecz3vLLBdutloLKsruUqEwHhOtQgb402iOLnyl14sHwgw5xfNpoKzQDXv/ta9k4o5yODKN/oo2t8kD7tUD6FMCQIArO2ibJZ3tdAiAqqn7MdFe7/pR8SH9+6s0+J2MKWyvtl2KC0mO9n7mJorNQISdL0Z2dBrm3G8laKLcmASaiMHSiXHp5BCOgRa7JWuAavTFJWR8XKZnFM/WI6WvR9zpD9Ev6wMWkb4A1G+8G3Zv+Ap3DGlqtlCGdOeqmj9PIs6QpXSkESticDUNuyiwB3UpeYng3b+lFVOi/SaQHeRgKndfzA/cDGSXdu4Ygfq20Vkp2jLBEQKtqJSLUb/rKIjuNThIKY1tMMAjQhwq5qogKHHa7w2Qrkz3SYZXkRV2Ns="
script:
- ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
