language: java
jdk:
- oraclejdk8
addons:
  sonarqube: true
env:
  global:
  - secure: tHcEx2Mabx5BnCHH+akF9ZyjhMnYKAs9Fn+R40XV2JsESfQH6nM60EEjyG1nJfxJ0XYQhRLaIIO76yF8jzKvSlLEOWPAL067hd3Ne0gTPGbDTRqNSbkcWo1roa0bPlwwgnWcOkIqloomvnMyDlwvqneF6AsRuXa54y1bLWtn1H41Dn0MoGMJk7GT4cLw0Z3WU+KAg17r5rlGUg6hUWu8nzkeVSjHzOtgkamo2BCOvvljjHoWBhKoudM7envn3ysc1XR9VveHiA3qJ/DSN+xNETd1/yMmcRA6IUOpAqeTTxpKqBl2jwfeg/nCTHgS/YVT80Dg3hc503P5AY7C+h0uGuNl+6uRcSVgR/6EOLEe47hBbXwm8+lThZfvs/p3ee1uE8XNSiYGo/1KCZZaiiFIU7qu7W/DrBSrAnjvMDyBt8XlSHYglNuUAl8qJXCcK++FPE+h3nHsG8lnIzlFph/ee+fXHAfv4pYxYmakJj6adyE/P7OIPOWFbHSHmkQ8tfDNvB75zSstNS5JyO3rPoiqNOSur8qwS90hZOKkVxhRHWGo3f7lvIvVywrLIR8dUKz6VLEFWmUy/u+1dEED0Xf144Yiy1Hs5ZAKn58ianSs8Fz8YidBQyl7XfZwLumsCE2t2sdMOiA30J4BWPpGAG0fwqBmBWkGgSdSPaQMZW9sZ1c=
script:
- ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
